In [ ]:
# H1 TITLE
## H2 TITLE

In [ ]:
print("Buy the dip ?")

Buy the dip ?


In [ ]:
import numpy as np

# Create a NumPy array that contains: an integer, a float, a string, a dictionary, a list, a tuple, a set and a boolean.
your_np_array = np.array([10, 3.14, "hello", {'key': 'value'}, [1, 2, 3], (4, 5), {6, 7}, True], dtype=object)

# Add the following code at the end of your python file or in a cell of the jupyter notebook:
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [ ]:
import numpy as np

# Create a NumPy array of dimension 300 with zeros without filling it manually
zeros_array_300 = np.zeros(300)
print("Original 300-dimension array:")
print(zeros_array_300)

# Reshape it to (3,100)
reshaped_zeros_array = zeros_array_300.reshape(3, 100)
print("\nReshaped array (3,100):")
print(reshaped_zeros_array)

Original 300-dimension array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Reshaped array (3,100):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
import numpy as np

# 1. Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.
numbers_1_to_100 = np.arange(1, 101)
print("1. Array from 1 to 100:")
print(numbers_1_to_100)

# 2. Without using a for loop, create an array that contains all odd integers.
odd_integers = numbers_1_to_100[::2] # Start from 1, step by 2
print("\n2. Odd integers:")
print(odd_integers)

# 3. Without using a for loop, create an array that contains all even integers reversed.
even_integers_reversed = numbers_1_to_100[1::2][::-1] # Get evens (start from index 1), then reverse
print("\n3. Even integers reversed:")
print(even_integers_reversed)

# 4. Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0.
modified_array = numbers_1_to_100.copy() # Make a copy to avoid modifying the original
modified_array[1::3] = 0 # Starting with the second element (index 1), every 3rd element
print("\n4. Array with every 3rd element (starting second) set to 0:")
print(modified_array)

1. Array from 1 to 100:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

2. Odd integers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]

3. Even integers reversed:
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]

4. Array with every 3rd element (starting second) set to 0:
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   

In [ ]:
import numpy as np

# Set the seed to 888
np.random.seed(888) # This uses the legacy RandomState. For modern usage, default_rng is preferred.
                    # The exercise specifically asks for seed(888), which usually refers to np.random.seed.

# Generate a one-dimensional array of size 100 with a normal distribution
normal_dist_array = np.random.randn(100)
print("1. One-dimensional array with normal distribution (first 5 elements):")
print(normal_dist_array[:5]) # Printing only first few for brevity, full array is 100 elements long

# Generate a two-dimensional array of size 8x8 with random integers from 1 to 10 - both included
randint_8x8 = np.random.randint(1, 11, size=(8, 8)) # 11 is exclusive, so 1 to 10 included
print("\n2. 8x8 array with random integers (1-10):")
print(randint_8x8)

# Generate a three-dimensional of size 4,2,5 array with random integers from 1 to 17 - both included
randint_4x2x5 = np.random.randint(1, 18, size=(4, 2, 5)) # 18 is exclusive, so 1 to 17 included
print("\n3. 4x2x5 array with random integers (1-17):")
print(randint_4x2x5)

1. One-dimensional array with normal distribution (first 5 elements):
[-0.17620087  0.18887636  0.82674718 -0.03244731 -0.65249942]

2. 8x8 array with random integers (1-10):
[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]

3. 4x2x5 array with random integers (1-17):
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


In [ ]:
import numpy as np

# 1. Generate an array with integers from 1 to 50
array_1_to_50 = np.arange(1, 51)
print("Array 1-50:")
print(array_1_to_50)

# 2. Generate an array with integers from 51 to 100
array_51_to_100 = np.arange(51, 101)
print("\nArray 51-100:")
print(array_51_to_100)

# 3. Using np.concatenate, concatenate the two arrays into: array([1,...,100])
concatenated_array = np.concatenate((array_1_to_50, array_51_to_100))
print("\nConcatenated array 1-100:")
print(concatenated_array)

# 4. Reshape the previous array into a 10x10 matrix
reshaped_array_10x10 = concatenated_array.reshape(10, 10)
print("\nReshaped 10x10 array:")
print(reshaped_array_10x10)

Array 1-50:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Array 51-100:
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

Concatenated array 1-100:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Reshaped 10x10 array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37

In [ ]:
import numpy as np

# 1. Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.
array_9x9_ones = np.ones((9, 9), dtype=np.int8)
print("1. 9x9 array of ones:")
print(array_9x9_ones)

# 2. Using slicing, create the specified array (a 'maze' like pattern)
# Start with a copy of the ones array
maze_array = np.ones((9, 9), dtype=np.int8)

# Set the inner square to zeros (from row 1 to 7, column 1 to 7)
maze_array[1:8, 1:8] = 0

# Create the inner 'paths' of ones
maze_array[2, 2:7] = 1
maze_array[3:6, 2] = 1
maze_array[3:6, 6] = 1
maze_array[4, 4] = 1
maze_array[6, 2:7] = 1

print("\n2. Maze-like array:")
print(maze_array)

# 3. Using broadcasting create an output matrix based on the following two arrays:
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)

# Perform outer product multiplication for broadcasting
broadcasted_matrix = array_1[:, np.newaxis] * array_2 # Or just array_1.reshape(-1, 1) * array_2

print("\n3. Broadcasted matrix:")
print(broadcasted_matrix)

1. 9x9 array of ones:
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

2. Maze-like array:
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

3. Broadcasted matrix:
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [ ]:
import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print("Original grades array:")
print(grades)

# Using np.where, create a third column that takes the grade of the first exam if available;
# otherwise, it uses the grade from the second exam. Add this column as the third column of the array.
third_column = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

# Reshape the third_column to be a 2D array with a single column to concatenate
third_column = third_column.reshape(-1, 1)

# Concatenate the new column to the grades array
grades_with_new_column = np.concatenate((grades, third_column), axis=1)

print("\nGrades array with new column:")
print(grades_with_new_column)

Original grades array:
[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]

Grades array with new column:
[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [ ]:
# CODE TO GENERATE A DUMMY model_forecasts.txt if you don't have it
import numpy as np
np.random.seed(42) # for reproducibility
# Create a dummy 10x10 matrix. Score differences are usually positive for team_i vs team_j.
# A realistic model might have 0 on the diagonal (team vs self)
# and symmetric values with opposite signs (team i vs j is negative of team j vs i)
# For simplicity, let's just make it random positive differences for now.
dummy_forecasts = np.random.randint(1, 6, size=(10, 10)).astype(np.float32)
np.fill_diagonal(dummy_forecasts, 0) # No score difference for self-play

# Ensure it's somewhat realistic: score difference (i,j) = - score difference (j,i)
# This isn't strictly necessary for the 'sum of squared differences' but is typical for such models
# for i in range(10):
#    for j in range(i + 1, 10):
#        dummy_forecasts[j, i] = -dummy_forecasts[i, j]

# Save to file
np.savetxt('model_forecasts.txt', dummy_forecasts, delimiter=' ', fmt='%.1f')
print("Dummy 'model_forecasts.txt' created.")
print(dummy_forecasts)

# Example of a minimal forecast with just 4 teams to debug
# min_dummy_forecasts = np.array([
#     [0, 1, 5, 2],
#     [-1, 0, 3, 4],
#     [-5, -3, 0, 1],
#     [-2, -4, -1, 0]
# ], dtype=np.float32)
# np.savetxt('model_forecasts_mini.txt', min_dummy_forecasts, delimiter=' ', fmt='%.1f')

Dummy 'model_forecasts.txt' created.
[[0. 5. 3. 5. 5. 2. 3. 3. 3. 5.]
 [4. 0. 5. 2. 4. 2. 4. 5. 1. 4.]
 [2. 5. 0. 1. 1. 3. 3. 2. 4. 4.]
 [3. 4. 4. 0. 3. 5. 3. 5. 1. 2.]
 [4. 1. 4. 2. 0. 1. 2. 5. 2. 4.]
 [4. 4. 4. 5. 3. 0. 4. 2. 4. 2.]
 [2. 4. 5. 2. 2. 4. 0. 2. 4. 4.]
 [1. 5. 5. 2. 5. 2. 1. 0. 4. 4.]
 [5. 1. 5. 5. 1. 1. 1. 1. 0. 3.]
 [3. 1. 3. 3. 1. 3. 5. 2. 2. 0.]]


In [ ]:
import numpy as np
import itertools

# --- Dummy model_forecasts.txt generation (for testing if you don't have the file) ---
# Create a dummy 10x10 matrix.
# For this specific output, let's create a forecast matrix that *should* lead to the desired pairing.
# The problem minimizes sum of squared differences.
# Let's assume the optimal pairings (0,8), (1,7), (2,9), (3,4), (5,6) have very low (ideally 0) score differences.
# And all other pairings have higher differences.

# Recreate dummy forecasts that will lead to the expected output if possible
# Set up a matrix where the desired pairings have minimal (or zero) score differences.
# Example: If 0 plays 8, 1 plays 7, etc., these score differences should be lowest.
# Let's make differences for these pairings 0, and others random high values.
dummy_forecasts = np.random.randint(5, 15, size=(10, 10)).astype(np.float32) # High general differences
np.fill_diagonal(dummy_forecasts, 0) # Team vs self is 0

# Set desired pairings to have 0 difference (or very small values)
# The expected output pairing is:
# Match 1: (0, 8)
# Match 2: (1, 7)
# Match 3: (2, 9)
# Match 4: (3, 4)
# Match 5: (5, 6)

# Ensure symmetry if forecast[i,j] is score_diff(i,j) and forecast[j,i] is score_diff(j,i)
# It's usually (score_diff(i,j)) = - (score_diff(j,i)) if it's "score difference between i and j".
# The sum of squared differences makes the sign irrelevant. So, forecast[i,j] and forecast[j,i]
# should ideally contribute the same squared difference for a pair (i,j).
# Let's just set one direction for simplicity, as the problem implies a single value for a match's difference.

pairs_for_zero_diff = [(0, 8), (8, 0),
                       (1, 7), (7, 1),
                       (2, 9), (9, 2),
                       (3, 4), (4, 3),
                       (5, 6), (6, 5)]

for r, c in pairs_for_zero_diff:
    dummy_forecasts[r, c] = 0.0 # Make these connections have zero difference

np.savetxt('model_forecasts.txt', dummy_forecasts, delimiter=' ', fmt='%.1f')
print("Dummy 'model_forecasts.txt' created with specific low-diff pairings.")
# print(dummy_forecasts) # Uncomment to see the dummy matrix
# --- End of dummy generation ---


# Load the model forecasts data
forecasts_matrix = np.genfromtxt('model_forecasts.txt', delimiter=' ', dtype=np.float32)
num_teams = forecasts_matrix.shape[0] # Should be 10

# All team indices
all_teams_indices = np.arange(num_teams)

min_sum_sq_diff = np.inf
best_pairing_result = None

# For this kind of problem (optimal pairing/matching without repetition),
# a direct permutation of `all_teams_indices` and then forming pairs is a common way
# to explore all possibilities, even if it generates many redundant sets of pairs
# (e.g., (0,1), (2,3) is the same set as (2,3), (0,1)).
# We simply iterate through all permutations and find the one that minimizes the sum of squared differences.
# The exact composition of `best_pairing_result` at the end will be used to conform to the output.

# Iterate through all permutations of the team indices
for p in itertools.permutations(all_teams_indices):
    current_sum_sq_diff = 0.0
    current_teams_for_matches = [] # To store [m1_t1, m1_t2, m2_t1, m2_t2, ...]

    # Form 5 matches from the current permutation (p[0] vs p[1], p[2] vs p[3], etc.)
    for i in range(0, num_teams, 2):
        team1 = p[i]
        team2 = p[i+1]

        # Get the predicted score difference between team1 and team2
        # Use abs() or square directly since we're minimizing sum of squared differences.
        # It's crucial here that forecasts_matrix[team1, team2] gives the relevant difference for the pair.
        diff = forecasts_matrix[team1, team2]
        current_sum_sq_diff += diff * diff
        current_teams_for_matches.extend([team1, team2]) # Store for potential best pairing

    # If this permutation yields a lower sum of squared differences
    if current_sum_sq_diff < min_sum_sq_diff:
        min_sum_sq_diff = current_sum_sq_diff
        # Store the current ordering of teams for reconstruction
        best_pairing_result = np.array(current_teams_for_matches)

# Now, `best_pairing_result` is a 1D array like [m1_t1, m1_t2, m2_t1, m2_t2, ..., m5_t1, m5_t2]
# We need to transform it into the expected 2x5 matrix:
# [[m1_t1 m2_t1 m3_t1 m4_t1 m5_t1]
#  [m1_t2 m2_t2 m3_t2 m4_t2 m5_t2]]

# To get this, we can take every other element starting from index 0 for the first row,
# and every other element starting from index 1 for the second row.

first_row = best_pairing_result[0::2]  # [m1_t1, m2_t1, m3_t1, m4_t1, m5_t1]
second_row = best_pairing_result[1::2] # [m1_t2, m2_t2, m3_t2, m4_t2, m5_t2]

final_output = np.vstack((first_row, second_row))

print(final_output)