In [1]:
# H1 TITLE
## H2 TITLE

In [ ]:
print("Buy the dip ?")

Buy the dip ?


In [ ]:
# Exercise 1: Your first NumPy array
import numpy as np

# Create a NumPy array that contains: an integer, a float, a string, a dictionary, a list, a tuple, a set and a boolean.
your_np_array = np.array([10, 3.14, "hello", {'key': 'value'}, [1, 2, 3], (4, 5), {6, 7}, True], dtype=object)

# Add the following code at the end of your python file or in a cell of the jupyter notebook:
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [ ]:
# Exercise 2: Zeros
import numpy as np

# Create a NumPy array of dimension 300 with zeros without filling it manually
zeros_array_300 = np.zeros(300)
print("Original 300-dimension array:")
print(zeros_array_300)

# Reshape it to (3,100)
reshaped_zeros_array = zeros_array_300.reshape(3, 100)
print("\nReshaped array (3,100):")
print(reshaped_zeros_array)

Original 300-dimension array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Reshaped array (3,100):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
# Exercise 3: slicing
import numpy as np

# 1. Create a NumPy array of dimension 1 that contains all integers from 1 to 100 ordered.
numbers_1_to_100 = np.arange(1, 101)
print("1. Array from 1 to 100:")
print(numbers_1_to_100)

# 2. Without using a for loop, create an array that contains all odd integers.
odd_integers = numbers_1_to_100[::2] # Start from 1, step by 2
print("\n2. Odd integers:")
print(odd_integers)

# 3. Without using a for loop, create an array that contains all even integers reversed.
even_integers_reversed = numbers_1_to_100[1::2][::-1] # Get evens (start from index 1), then reverse
print("\n3. Even integers reversed:")
print(even_integers_reversed)

# 4. Using array of Q1, set the value of every 3 elements of the list (starting with the second) to 0.
modified_array = numbers_1_to_100.copy() # Make a copy to avoid modifying the original
modified_array[1::3] = 0 # Starting with the second element (index 1), every 3rd element
print("\n4. Array with every 3rd element (starting second) set to 0:")
print(modified_array)

1. Array from 1 to 100:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

2. Odd integers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]

3. Even integers reversed:
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]

4. Array with every 3rd element (starting second) set to 0:
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   

In [ ]:
# Exercise 4: Random

import numpy as np

# Set the seed to 888
np.random.seed(888) # This uses the legacy RandomState. For modern usage, default_rng is preferred.
                    # The exercise specifically asks for seed(888), which usually refers to np.random.seed.

# Generate a one-dimensional array of size 100 with a normal distribution
normal_dist_array = np.random.randn(100)
print("1. One-dimensional array with normal distribution (first 5 elements):")
print(normal_dist_array[:5]) # Printing only first few for brevity, full array is 100 elements long

# Generate a two-dimensional array of size 8x8 with random integers from 1 to 10 - both included
randint_8x8 = np.random.randint(1, 11, size=(8, 8)) # 11 is exclusive, so 1 to 10 included
print("\n2. 8x8 array with random integers (1-10):")
print(randint_8x8)

# Generate a three-dimensional of size 4,2,5 array with random integers from 1 to 17 - both included
randint_4x2x5 = np.random.randint(1, 18, size=(4, 2, 5)) # 18 is exclusive, so 1 to 17 included
print("\n3. 4x2x5 array with random integers (1-17):")
print(randint_4x2x5)

1. One-dimensional array with normal distribution (first 5 elements):
[-0.17620087  0.18887636  0.82674718 -0.03244731 -0.65249942]

2. 8x8 array with random integers (1-10):
[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]

3. 4x2x5 array with random integers (1-17):
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]


In [ ]:
# Exercise 5: Split, concatenate, reshape arrays



import numpy as np

# 1. Generate an array with integers from 1 to 50
array_1_to_50 = np.arange(1, 51)
print("Array 1-50:")
print(array_1_to_50)

# 2. Generate an array with integers from 51 to 100
array_51_to_100 = np.arange(51, 101)
print("\nArray 51-100:")
print(array_51_to_100)

# 3. Using np.concatenate, concatenate the two arrays into: array([1,...,100])
concatenated_array = np.concatenate((array_1_to_50, array_51_to_100))
print("\nConcatenated array 1-100:")
print(concatenated_array)

# 4. Reshape the previous array into a 10x10 matrix
reshaped_array_10x10 = concatenated_array.reshape(10, 10)
print("\nReshaped 10x10 array:")
print(reshaped_array_10x10)

Array 1-50:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Array 51-100:
[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

Concatenated array 1-100:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Reshaped 10x10 array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37

In [ ]:
# Exercise 6: Broadcasting and Slicing
import numpy as np

# 1. Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.
array_9x9_ones = np.ones((9, 9), dtype=np.int8)
print("1. 9x9 array of ones:")
print(array_9x9_ones)

# 2. Using slicing, create the specified array (a 'maze' like pattern)
# Start with a copy of the ones array
maze_array = np.ones((9, 9), dtype=np.int8)

# Set the inner square to zeros (from row 1 to 7, column 1 to 7)
maze_array[1:8, 1:8] = 0

# Create the inner 'paths' of ones
maze_array[2, 2:7] = 1
maze_array[3:6, 2] = 1
maze_array[3:6, 6] = 1
maze_array[4, 4] = 1
maze_array[6, 2:7] = 1

print("\n2. Maze-like array:")
print(maze_array)

# 3. Using broadcasting create an output matrix based on the following two arrays:
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)

# Perform outer product multiplication for broadcasting
broadcasted_matrix = array_1[:, np.newaxis] * array_2 # Or just array_1.reshape(-1, 1) * array_2

print("\n3. Broadcasted matrix:")
print(broadcasted_matrix)

1. 9x9 array of ones:
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

2. Maze-like array:
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

3. Broadcasted matrix:
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [ ]:
# 4.Exercise 7: NaN

import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
print("Original grades array:")
print(grades)

# Using np.where, create a third column that takes the grade of the first exam if available;
# otherwise, it uses the grade from the second exam. Add this column as the third column of the array.
third_column = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

# Reshape the third_column to be a 2D array with a single column to concatenate
third_column = third_column.reshape(-1, 1)

# Concatenate the new column to the grades array
grades_with_new_column = np.concatenate((grades, third_column), axis=1)

print("\nGrades array with new column:")
print(grades_with_new_column)

Original grades array:
[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]

Grades array with new column:
[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [5]:
# Exercise 8: Wine
import numpy as np
# 1. Load the data using genfromtxt, specifying the delimiter as ';' with excluding the headers, and optimize the numpy array size by reducing the data types. Use np.float32 and verify that the resulting numpy array weighs 76800 bytes.
data = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1, dtype=np.float32)

print("Array shape:", data.shape)     
print("Array dtype:", data.dtype)      
print("Array size in bytes:", data.nbytes, "\n")  

# 2. Display the 2nd, 7th, and 12th rows as a two-dimensional array. Exclude np.nan values if present.
rows = data[[1, 6, 11], :]
rows_no_nan = rows[~np.isnan(rows).any(axis=1)]
np.set_printoptions(suppress=True, precision=3)
print(rows_no_nan, "\n")

# 3. Determine if there is any wine in the dataset with an alcohol percentage greater than 20%. Return True or False.
has_high_alcohol = np.any(data[:, -1] > 20)

print(has_high_alcohol, "\n")

#4. Calculate the average alcohol percentage across all wines in the dataset. Exclude np.nan values if present.
alcohol = data[:, 10]
avg_alcohol = np.nanmean(alcohol)
print(avg_alcohol, "\n")

#5. Compute various statistical measures (minimum, maximum, 25th percentile, 50th percentile, 75th percentile and the mean for the pH values).
ph_values = data[:, 8]
ph_values = ph_values[~np.isnan(ph_values)]
ph_min = np.min(ph_values)
ph_max = np.max(ph_values)
ph_25 = np.percentile(ph_values, 25)
ph_50 = np.percentile(ph_values, 50)   # same as median
ph_75 = np.percentile(ph_values, 75)
ph_mean = np.mean(ph_values)

print("Minimum:", ph_min)
print("Maximum:", ph_max)
print("25th Percentile:", ph_25)
print("50th Percentile:", ph_50)
print("75th Percentile:", ph_75)
print("Mean:", ph_mean, "\n")

#6.Find the average quality score of wines with the 20% least sulphate content.

sulphates = data[:, 9]
quality = data[:, 11]

mask = ~np.isnan(sulphates) & ~np.isnan(quality)
sulphates = sulphates[mask]
quality = quality[mask]

perc20 = np.percentile(sulphates, 20)

low_sulphates_mask = sulphates <= perc20

low_sulphates_quality = quality[low_sulphates_mask]

avg_quality_low_sulphates = np.mean(low_sulphates_quality)

print("Average quality (lowest 20% sulphates):", avg_quality_low_sulphates, "\n")

# 7.Compute the mean of all variables for wines with the best quality. Also, do the same for wines with the worst quality.

quality = data[:, 11]

mask = ~np.isnan(quality)
data_no_nan = data[mask]
quality_no_nan = quality[mask]

max_quality = np.max(quality_no_nan)
min_quality = np.min(quality_no_nan)

best_mask = quality_no_nan == max_quality
worst_mask = quality_no_nan == min_quality

mean_best_quality = np.mean(data_no_nan[best_mask], axis=0)
mean_worst_quality = np.mean(data_no_nan[worst_mask], axis=0)

print("Mean values for best quality wines:\n", mean_best_quality, "\n")

print("Mean values for worst quality wines:\n", mean_worst_quality)




Array shape: (1599, 12)
Array dtype: float32
Array size in bytes: 76752 

[[  7.8     0.88    0.      2.6     0.098  25.     67.      0.997   3.2
    0.68    9.8     5.   ]
 [  7.9     0.6     0.06    1.6     0.069  15.     59.      0.996   3.3
    0.46    9.4     5.   ]
 [  7.5     0.5     0.36    6.1     0.071  17.    102.      0.998   3.35
    0.8    10.5     5.   ]] 

False 

10.422984 

Minimum: 2.74
Maximum: 4.01
25th Percentile: 3.2100000381469727
50th Percentile: 3.309999942779541
75th Percentile: 3.4000000953674316
Mean: 3.3111134 

Average quality (lowest 20% sulphates): 5.216216 

Mean values for best quality wines:
 [ 8.567  0.423  0.391  2.578  0.068 13.278 33.444  0.995  3.267  0.768
 12.094  8.   ] 

Mean values for worst quality wines:
 [ 8.36   0.885  0.171  2.635  0.122 11.    24.9    0.997  3.398  0.57
  9.955  3.   ]


In [11]:
# Exercise 9: Football tournament

import numpy as np
import itertools


forecasts = np.genfromtxt("model_forecasts.txt", delimiter=",")

# Number of teams
n = forecasts.shape[0]

# All possible pairings (unordered, so (i,j) same as (j,i))
pairs = [(i, j) for i in range(n) for j in range(i+1, n)]

# Function to compute squared sum for a given pairing set
def score_for_matching(matching):
    diffs = [forecasts[i, j] for (i, j) in matching]
    return np.sum(np.square(diffs))

# Generate all possible perfect matchings using itertools
def generate_matchings(teams):
    if len(teams) == 0:
        return [[]]
    first = teams[0]
    matchings = []
    for i in range(1, len(teams)):
        for rest in generate_matchings(teams[1:i] + teams[i+1:]):
            matchings.append([(first, teams[i])] + rest)
    return matchings

# Generate all matchings for 10 teams
all_matchings = generate_matchings(list(range(n)))

# Find the best matching (minimum squared sum)
best_matching = min(all_matchings, key=score_for_matching)

# Convert into required 2x5 format
result = np.array(best_matching).T

print("Best matching:\n", result)


Best matching:
 [[0 1 2 3 5]
 [8 7 9 4 6]]
